exclude: "/tinymce/"
fail_fast: false
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 21.4b2
    hooks:
      - id: black
        exclude: "^.*/migrations/.*.py$"

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        exclude: "^.*/migrations/.*.py$"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.3.1
    hooks:
      - id: eslint
        args: [--fix]
        additional_dependencies:
          - eslint@7.3.1
          - babel-eslint@10.0.3
          - eslint-config-google@0.14.0
        exclude: "^.*\\.min\\..*$"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.0
    hooks:
      - id: prettier
        files: \.js$
        exclude: "^.*\\.min\\..*$"

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        args: [--fix]
        exclude: "^.*\\.min\\..*$"
        additional_dependencies:
          - stylelint@13.6.1
          - stylelint-config-recommended-scss@4.2.0
          - stylelint-config-recommended@3.0.0
          - stylelint-order@4.1.0
          - stylelint-scss@3.18.0

  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: safety check
        language: system
        always_run: true
        exclude: ".*"
      - id: npm-audit
        name: npm-audit
        language: system
        entry: npm audit --audit-level=high
        always_run: true
        exclude: ".*"
