default_language_version:
  python: python3.8

exclude: "^$"

fail_fast: false

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.12.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/rtts/djhtml
    rev: v1.5.2
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint

  - repo: https://github.com/pycqa/isort
    rev: 5.11.3
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: "^.*/migrations/.*.py$"
        args: [--line-length=79, --safe]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.12.6
          - flake8-comprehensions==3.10.1
          - flake8-no-pep420==2.3.0
          - flake8-tidy-imports==4.8.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        args: [--fix]
        additional_dependencies:
          - eslint@7.32.0
          - eslint-config-developit@1.2.0
          - eslint-config-google@0.14.0
          - eslint-config-preact@1.1.4
          - eslint-config-prettier@8.3.0
          - eslint-plugin-prettier@3.4.0
          - "@babel/eslint-parser@7.14.7"
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
        exclude: "^.*\\.min\\..*$"
        files: \.[jt]sx?$
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.1
        files: \.js$
        exclude: "^.*\\.min\\..*$"

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        args: [--fix]
        exclude: "^.*\\.min\\..*$"
        additional_dependencies:
          - postcss-scss@2.1.1
          - stylelint@14.16.0
          - stylelint-config-recommended-scss@8.0.0
          - stylelint-config-recommended@9.0.0
          - stylelint-order@5.0.0
          - stylelint-scss@4.3.0

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
        name: safety
        always_run: true
        exclude: ".*"
        verbose: true
        args: ["requirements/requirements-prod-aws.txt", "--ignore=51619,53048,53298,53299,53301,53302,53303,53304,53305,53306,53307,35462,59062,59473,59956,60223,60224,60225,62105,61893,62452",]

  - repo: local
    hooks:
      - id: npm-audit
        name: npm-audit
        language: system
        entry: npm audit --audit-level=critical
        always_run: true
        exclude: ".*"
