exclude: "^$"
fail_fast: false
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v1.9.1
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.9.0
    hooks:
      - id: eslint
  - repo: https://github.com/prettier/prettier
    rev: 1.15.2
    hooks:
      - id: prettier
        types: [scss, javascript]
