default_language_version:
  python: python3.8

exclude: "/tinymce/"

fail_fast: false

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/rtts/djhtml
    rev: v1.5.1
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: "^.*/migrations/.*.py$"
        args: [--line-length=79, --safe]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.7.1
          - flake8-no-pep420==2.3.0
          - flake8-comprehensions==3.10.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.30.0
    hooks:
      - id: eslint
        args: [--fix]
        additional_dependencies:
          - eslint@7.30.0
          - eslint-config-developit@1.2.0
          - eslint-config-google@0.14.0
          - eslint-config-preact@1.1.4
          - eslint-config-prettier@8.3.0
          - eslint-plugin-prettier@3.4.0
          - "@babel/eslint-parser@7.14.7"
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
        exclude: "^.*\\.min\\..*$"
        files: \.[jt]sx?$
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.3.2
        files: \.js$
        exclude: "^.*\\.min\\..*$"

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        args: [--fix]
        exclude: "^.*\\.min\\..*$"
        additional_dependencies:
          - stylelint@13.13.1
          - stylelint-config-recommended-scss@4.3.0
          - stylelint-config-recommended@5.0.0
          - stylelint-order@4.1.0
          - stylelint-scss@3.19.0

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.2
    hooks:
      - id: python-safety-dependencies-check
        name: safety
        always_run: true
        exclude: ".*"
        verbose: true
        args: ["requirements/requirements-prod-aws.txt"]

  - repo: local
    hooks:
      - id: npm-audit
        name: npm-audit
        language: system
        entry: npm audit --audit-level=high
        always_run: true
        exclude: ".*"
