version: "3.7"

services:
  app:
    build: .
    command: gunicorn dalite.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      DALITE_DB_HOST: host.docker.internal
    volumes:
      - static:/code/static

  nginx:
    build: ./nginx
    ports:
      - 1337:8080
    depends_on:
      - app
    volumes:
      - static:/static

volumes:
  static:
