[tool.black]
line_length = 79
exclude = '''
/(
    \.git
/)
'''

[tool.coverage.run]
source = ["dalite", "peerinst", "quality", "tos"]
omit = ["*/tests/*", "*/migrations/*"]

[tool.coverage.report]
show_missing = true
