[tool.curlylint.rules]
html_has_lang = true
image_alt = true
meta_viewport = true

[tool.black]
target-version = ['py38']
line_length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
/)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
