# Generated by Django 3.2.20 on 2023-11-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0114_auto_20231109_0113'),
        ('reputation', '0013_auto_20200103_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convincingrationalescriterion',
            name='for_reputation_types',
        ),
        migrations.RemoveField(
            model_name='nanswerscriterion',
            name='for_reputation_types',
        ),
        migrations.RemoveField(
            model_name='nquestionscriterion',
            name='for_reputation_types',
        ),
        migrations.RemoveField(
            model_name='questionlikedcriterion',
            name='for_reputation_types',
        ),
        migrations.RemoveField(
            model_name='rationaleevaluationcriterion',
            name='for_reputation_types',
        ),
        migrations.RemoveField(
            model_name='reputation',
            name='reputation_type',
        ),
        migrations.AlterUniqueTogether(
            name='reputationhistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reputationhistory',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='studentrationaleevaluationcriterion',
            name='for_reputation_types',
        ),
        migrations.RemoveField(
            model_name='usescriterion',
            name='reputation_type',
        ),
        migrations.DeleteModel(
            name='CommonRationaleChoicesCriterion',
        ),
        migrations.DeleteModel(
            name='ConvincingRationalesCriterion',
        ),
        migrations.DeleteModel(
            name='NAnswersCriterion',
        ),
        migrations.DeleteModel(
            name='NQuestionsCriterion',
        ),
        migrations.DeleteModel(
            name='QuestionLikedCriterion',
        ),
        migrations.DeleteModel(
            name='RationaleEvaluationCriterion',
        ),
        migrations.DeleteModel(
            name='Reputation',
        ),
        migrations.DeleteModel(
            name='ReputationHistory',
        ),
        migrations.DeleteModel(
            name='ReputationType',
        ),
        migrations.DeleteModel(
            name='StudentRationaleEvaluationCriterion',
        ),
        migrations.DeleteModel(
            name='UsesCriterion',
        ),
    ]
