__all__ = [
    "AssignmentSerializer",
    "AnswerSerializer",
    "CategorySerializer",
    "CollectionSerializer",
    "DisciplineSerializer",
    "FeedbackReadSerialzer",
    "FeedbackWriteSerialzer",
    "QuestionSerializer",
    "RankSerializer",
    "StudentGroupAssignmentAnswerSerializer",
    "StudentGroupAssignmentSerializer",
    "StudentGroupSerializer",
    "TeacherSearchSerializer",
    "TeacherSerializer",
    "UserSerializer",
]

from .peerinst import (  # noqa
    AnswerSerializer,
    AssignmentSerializer,
    CategorySerializer,
    CollectionSerializer,
    DisciplineSerializer,
    FeedbackReadSerialzer,
    FeedbackWriteSerialzer,
    QuestionSerializer,
    RankSerializer,
    StudentGroupAssignmentAnswerSerializer,
    StudentGroupAssignmentSerializer,
    StudentGroupSerializer,
    TeacherSearchSerializer,
    TeacherSerializer,
    UserSerializer,
)
