# Generated by Django 1.11.22 on 2019-08-15 21:50


import django.db.models.deletion
from django.db import migrations, models

import peerinst.models.question


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0085_auto_20190810_1400")]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="collection",
            name="assignments",
            field=models.ManyToManyField(blank=True, to="peerinst.Assignment"),
        ),
    ]
