# Generated by Django 2.2.24 on 2021-07-04 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peerinst', '0093_auto_20200219_2152_squashed_0106_delete_studentgroupcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='saltisemember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
