# Generated by Django 2.2.24 on 2021-07-07 15:08

import django.db.models.deletion
from django.db import migrations, models

import peerinst.models.question


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0094_saltisemember_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ('title',), 'verbose_name': 'discipline', 'verbose_name_plural': 'disciplines'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('title',), 'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Enter the title of the question category.', max_length=100, unique=True, validators=[peerinst.models.question.no_hyphens], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(help_text='Enter the title of the discipline.', max_length=100, unique=True, validators=[peerinst.models.question.no_hyphens], verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='question',
            name='discipline',
            field=models.ForeignKey(blank=True, help_text='Optional. Select the discipline to which this item should be associated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='peerinst.Discipline'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(help_text='Enter the title of the subject.', max_length=100, unique=True, validators=[peerinst.models.question.no_hyphens], verbose_name='Subject'),
        ),
    ]
