# Generated by Django 2.2.24 on 2021-07-13 21:21

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0095_auto_20210707_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='conclusion_page',
            field=models.TextField(blank=True, help_text='Any notes you would like to leave for students to read that will be shown after the last question of the assignment.', null=True, verbose_name='Post Assignment Notes'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, help_text='Notes you would like keep for yourself (or other teachers) regarding this assignment.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='identifier',
            field=models.CharField(help_text='The assignment identifier is used to access the assignment through an LMS (e.g. Moodle).  Only use letters, numbers and the underscore for the identifier.  Max length is 100 characters.', max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), django.core.validators.MinLengthValidator(2)], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='intro_page',
            field=models.TextField(blank=True, help_text='Any special instructions you would like students to read before they start the assignment.', null=True, verbose_name='Assignment Cover Page'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peerinst.Assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(help_text="The assignment title can be anything you'd like, but it is helpful for indexing if it is a descriptive phrase, e.g. 'Mechanics - Energy Diagrams 1'.  Max length is 200 characters.", max_length=200, verbose_name='Title'),
        ),
    ]
