# Generated by Django 2.2.24 on 2021-07-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0096_auto_20210713_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='saltisemember',
            name='expert',
            field=models.BooleanField(default=False, verbose_name='SALTISE fellow'),
        ),
    ]
