# Generated by Django 2.2.24 on 2021-07-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0097_saltisemember_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='archived_questions',
            field=models.ManyToManyField(blank=True, related_name='archived_questions', to='peerinst.Question'),
        ),
    ]
