# Generated by Django 2.2.24 on 2021-07-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0098_teacher_archived_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peerinst.Institution'),
        ),
    ]
