# Generated by Django 2.2.24 on 2021-07-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0100_studentgroup_mode_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalLMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='\n            URL found in institutional LMS LTI parameter\n            `tool_consumer_instance_guid`.\n            ', max_length=100, unique=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peerinst.Institution')),
            ],
            options={
                'verbose_name': 'institution_lms_url',
                'verbose_name_plural': 'institution_lms_urls',
            },
        ),
    ]
