# Generated by Django 2.2.24 on 2021-07-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0101_institutionallms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
    ]
