# Generated by Django 2.2.24 on 2021-07-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0104_auto_20210721_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='students', through='peerinst.StudentGroupMembership', to='peerinst.StudentGroup'),
        ),
    ]
