# Generated by Django 2.2.24 on 2021-07-31 04:06

from django.db import migrations, models

import peerinst.models.question


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0105_auto_20210721_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionflagreason',
            name='title',
            field=models.CharField(choices=[('Clarification needed', 'The question, or one of the answer choices, is unclear.'), ('No Expert Rationale', 'A rationale must be provided for each correct answer choice that would represent the opinion of an expert in the discipline.'), ('No seed rationales', 'A sample answer must be provided for each answer choice, whether correct or incorrect.'), ('Potential copyright issues', 'Some part of the question, perhaps the image or attached video, may come from a copyrighted source.'), ('Wrong answer marked as correct', 'Wrong answer marked as correct')], default='Clarification needed', help_text='Reason for flagging a question.', max_length=100, unique=True, validators=[peerinst.models.question.no_hyphens], verbose_name='Reason for flagging a question'),
        ),
    ]
