# Generated by Django 2.2.20 on 2021-04-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0105_auto_20200903_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGroupCourse',
        ),
    ]
