# Generated by Django 2.2.24 on 2021-07-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0105_auto_20210721_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='archived_assignments',
            field=models.ManyToManyField(blank=True, related_name='archived_assignments', to='peerinst.Assignment'),
        ),
    ]
