# Generated by Django 2.2.24 on 2021-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0106_auto_20210731_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionflagreason',
            name='title',
            field=models.CharField(choices=[('Clarification needed', 'The question, or one of the answer choices, is unclear.'), ('No Expert Rationale', '\n                A rationale must be provided for each correct answer                 choice that would represent the opinion of an expert in                 the discipline.\n                '), ('No seed rationales', '\n                A sample answer must be provided for each answer choice,                 whether correct or incorrect.\n                '), ('Potential copyright issues', '\n                Some part of the question, perhaps the image or                 attached video, may come from a copyrighted source.\n                '), ('Wrong answer marked as correct', '\n                Wrong answer marked as correct\n                ')], default='Clarification needed', help_text='Reason for flagging a question.', max_length=100, unique=True, verbose_name='Reason for flagging a question'),
        ),
    ]
