# Generated by Django 2.2.24 on 2021-08-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0107_auto_20210731_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionflagreason',
            name='title',
            field=models.CharField(choices=[('Clarification needed', 'The question, or one of the answer choices, is unclear.'), ('Potential copyright issues', '\n                Some part of the question, perhaps the image or                 attached video, may come from a copyrighted source.\n                '), ('Wrong answer marked as correct', '\n                Wrong answer marked as correct\n                ')], default='Clarification needed', help_text='Reason for flagging a question.', max_length=100, unique=True, verbose_name='Reason for flagging a question'),
        ),
    ]
