# Generated by Django 2.2.28 on 2022-07-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0109_auto_20220728_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltievent',
            name='event_log',
        ),
    ]
