# Generated by Django 3.2.15 on 2022-08-09 03:11

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0110_remove_ltievent_event_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='identifier',
            field=models.CharField(help_text='The assignment identifier is used to access the assignment through an LMS (e.g. Moodle).  Only use letters, numbers and the underscore for the identifier.  Max length is 100 characters.', max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), django.core.validators.MinLengthValidator(2)], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='mode_created',
            field=models.CharField(choices=[('LTI', 'LTI'), ('STANDALONE', 'STANDALONE'), ('LTI_STANDALONE', 'LTI_STANDALONE')], default='STANDALONE', max_length=20),
        ),
    ]
