# Generated by Django 3.2.20 on 2023-11-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0111_auto_20220809_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='assignment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='peerinst.assignment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rationale_selection_algorithm',
            field=models.CharField(choices=[('simple', 'Simple random rationale selection'), ('prefer_expert_and_highly_voted', 'Prefer expert and highly voted rationales')], default='prefer_expert_and_highly_voted', help_text='The algorithm to use for choosing the rationales presented to students during question review.  This option is ignored if you selected sequential review.', max_length=100, verbose_name='Rationale selection algorithm'),
        ),
    ]
