# Generated by Django 3.2.20 on 2023-11-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0112_auto_20231104_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peerinst.assignment'),
        ),
    ]
