# Generated by Django 3.2.20 on 2023-11-19 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0113_alter_answervote_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestions',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerinst.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerinst.question'),
        ),
    ]
