# Generated by Django 3.2.20 on 2023-11-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0113_alter_answervote_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='reputation',
        ),
    ]
