# Generated by Django 3.2.20 on 2023-11-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0114_auto_20231119_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroupassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peerinst.assignment'),
        ),
    ]
