# Generated by Django 3.2.20 on 2023-11-20 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0115_alter_studentgroupassignment_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peerinst.discipline'),
        ),
    ]
