# Generated by Django 3.2.22 on 2023-11-30 03:18

from django.db import migrations, models
import peerinst.models.question
import peerinst.validators


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0116_alter_collection_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[peerinst.models.no_hyphens], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[peerinst.models.no_hyphens], verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional. A video or simulation to include after the question text. All videos should include transcripts.  Only videos from youtube (i.e. https://www.youtube.com/embed/...) and simulations from phet (i.e. https://phet.colorado.edu/sims/html/...) are currently supported.', validators=[peerinst.validators.allowed_domain, peerinst.validators.allowed_scheme], verbose_name='Question video URL'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[peerinst.models.no_hyphens], verbose_name='Subject'),
        ),
    ]
