# Generated by Django 3.2.22 on 2023-11-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0114_auto_20231109_0113'),
        ('peerinst', '0117_auto_20231130_0318'),
    ]

    operations = [
    ]
