# Generated by Django 3.2.23 on 2024-01-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0118_merge_0114_auto_20231109_0113_0117_auto_20231130_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(help_text='Type to search and select at least one category for this question. You can select multiple categories.', to='peerinst.Category'),
        ),
    ]
