version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
        environment:
          DALITE_DB_PASSWORD: test key
    working_directory: ~/repo
    branches:
      only:
        - development
        - ci
    steps:
      - checkout
      - run:
          name: Build
          command: |
            sudo apt-get install yarn mariadb-dev
            sudo pip2 install virtualenv
            yarn global add gulp
            virtualenv .venv
            . .venv/bin/activate
            pip install -r requirements/dev-requirements.txt
            yarn install
            gulp build
