version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
        environment:
          DALITE_DB_PASSWORD: test key
    working_directory: ~/repo
    branches:
      only:
        - development
        - ci
    steps:
      - checkout
      - run:
          name: Build
          command: |
            pip install -r requirements/test-requirements.txt
            yarn install
            gulp build
