version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node-browsers
        environment:
          DALITE_DB_PASSWORD: test key
      - image: mariadb
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: dalite_ng
          MYSQL_USER: dalite
          MYSQL_PASSWORD: test key

    working_directory: ~/repo
    branches:
      only:
        - development
        - ci
    steps:
      - checkout
      - run:
          name: Build
          command: |
            sudo pip2 install virtualenv
            sudo yarn global add gulp
            virtualenv .venv
            . .venv/bin/activate
            pip install -r requirements/dev-requirements.txt
            tools/gen_secret_key.py > dalite/local_settings.py
            yarn install
            gulp build
      - run:
          name: Waiting for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Setup db
          command: |
            . .venv/bin/activate
            ./manage.py migrate
      - run:
          name: Tests
          command: |
            . .venv/bin/activate
            pytest --cov --create-db
