version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
  snyk: snyk/snyk@1.2.3
jobs:
  build:
    resource_class: medium
    docker:
      - image: cimg/python:3.8-browsers
        environment:
          DALITE_DB_PASSWORD: test key
          DALITE_DB_HOST: 127.0.0.1
          DALITE_DB_PORT: 3306
          MYSQL_ROOT_PASSWORD: mariadb
      - image: mariadb
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: dalite_ng
          MYSQL_USER: dalite
          MYSQL_PASSWORD: test key
          MYSQL_HOST: localhost
          MYSQL_ROOT_PASSWORD: mariadb
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: OS setup
          command: |
            sudo apt update
            sudo apt install mariadb-client
      - run:
          name: Create virtualenv and activate
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install --upgrade pip
      - run:
          name: Run safety
          command: |
            pip install safety
            safety check -r requirements/requirements-prod-aws.txt --key=$SAFETY_API_KEY --ignore=49733
      - run:
          name: Build
          command: |
            pip install -r requirements/requirements-dev.txt
            pip freeze
            python -m spacy download en_core_web_sm
            npm install --no-optional
            ./node_modules/gulp/bin/gulp.js build
      - snyk/scan:
          additional-arguments: --all-projects
          fail-on-issues: true
          token-variable: SNYK_TOKEN
      - run:
          name: Setup local_settings.py
          command: |
            tools/gen_secret_key.py > dalite/local_settings.py
            echo 'PIWIK_DOMAIN_PATH = "matomo.mydalite.org"' >> dalite/local_settings.py
            echo 'PIWIK_SITE_ID = "1"' >> dalite/local_settings.py
            echo 'PASSWORD_GENERATOR_NONCE = "secret key"' >> dalite/local_settings.py
            echo 'import os' >> dalite/local_settings.py
            echo 'BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))' >> dalite/local_settings.py
            echo 'EMAIL_SUBJECT_PREFIX = "SALTISE/S4 @ Dawson College: "' >> dalite/local_settings.py
            echo 'DEFAULT_FROM_EMAIL = "no-reply-SALTISES4@dawsoncollege.qc.ca"' >> dalite/local_settings.py
            echo 'EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"' >> dalite/local_settings.py
      - run:
          name: Waiting for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: DB setup
          command: |
            mysql --host=$DALITE_DB_HOST --port=$DALITE_DB_PORT -u root --password=$MYSQL_ROOT_PASSWORD -e "grant all privileges on test_dalite_ng.* to dalite@'%'"
            ./manage.py migrate
      - run:
          name: Collect static content and compress
          command: |
            ./manage.py collectstatic -c
            ./manage.py compress
      - store_artifacts:
          path: /home/circleci/repo/static
      - aws-s3/sync:
          from: /home/circleci/repo/static
          to: 's3://staging-courseflow-static'
      - run:
          name: Run tests
          command: |
            pytest --migrations --cov --create-db --reruns 1
