version: 2.0

jobs:
  build:
    machine: true
    branches:
      only:
        - development
    steps:
      - checkout
      - run:
         name: Fetch
         command: |
           ls -al
      - run:
          name: Test and coverage
          command: 'py.test --cov-config .coveragerc --cov=peerinst --cov=dalite --cov=tos'
      - store_artifacts:
          path: coverage.xml
          prefix: coverage
