version: 2
jobs:
  build:
    docker:
      - image: antoinelb/python2-yarn
    working_directory: ~/repo
    branches:
      only:
        - development
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements/dev-requirements.txt
            yarn install
      - run:
          name: Run tests
          command: |
            pytest --cov
