# Generated by Django 3.2.20 on 2023-11-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0002_auto_20180808_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtype',
            name='show_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
