# Generated by Django 3.2.20 on 2023-11-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blinkassignment',
            name='blinkquestions',
        ),
        migrations.RemoveField(
            model_name='blinkassignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='blinkassignmentquestion',
            name='blinkassignment',
        ),
        migrations.RemoveField(
            model_name='blinkassignmentquestion',
            name='blinkquestion',
        ),
        migrations.RemoveField(
            model_name='blinkquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='blinkquestion',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='blinkround',
            name='question',
        ),
        migrations.DeleteModel(
            name='BlinkAnswer',
        ),
        migrations.DeleteModel(
            name='BlinkAssignment',
        ),
        migrations.DeleteModel(
            name='BlinkAssignmentQuestion',
        ),
        migrations.DeleteModel(
            name='BlinkQuestion',
        ),
        migrations.DeleteModel(
            name='BlinkRound',
        ),
    ]
